- .gitignore
- build.gradle
- src/main/java/CIServer.java
Added the cod to connect between server and firebase database (method: updateDatabase). Also example cod for set in firebase or get information i firebase. 
close#20
> [ADD], the connetion between server and firebase #20

- src/test/java/TestClass.java
Added the missing test for JsonParser close #27
> [ADD] - Added tests for JsonParser

- build.gradle
- src/main/java/ServerControl.java
- src/test/java/TestClass.java
Added command control class with the use of proces builder to CITool. Also added
logging method for the data that is returned.  Added one mocked test for
run command and one for the log method to the test class.
Tests described in code. close #30 close #31
> [ADD] - Added command control class according to issue #30 #31

- src/main/java/ServerControl.java
- src/test/java/TestClass.java
Added a method that check the os on the machine and then returns shell
and close command. Added a test in test class for method. close #33
> [ADD] - Added a method for os and shell check according to issue #33

- src/main/java/ServerControl.java
Added a method that uses the runCommand method from ServerControl.
The method uses ./gradle build, git clone, git checkout and cd.
Futher enhancement need to remove directory created while cloning. No
test needed, since the test are the same as for
run command. Test may be added in the future. close #38
> [ADD] - Added a methods for Clone and build according to issue #38

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/index.js
- client/src/util/buildsContext.js
- client/src/util/firebase.js
Buildscontext serves as the container for all the data from firebase, to prevent fetching the same data multiple times, as well as allow easy access for all of the components.
> [ADD] Added buildscontext

- client/.gitignore
Included a local copy of firebase api details in local file, and added it to gitignore
> [ADD] Added firebase api details to local .env and updated gitignore

- src/main/java/CIServer.java
- src/main/java/Firebase/PullRequest.java
When a pull request the database will update whit information from the request. 
The connection to the database is also done once. 
close #65
> [ADD], Updates database when a pull request is done #65

- src/test/java/TestClass.java
renamed the test to testGetOsShell from testgetOsShell
> [FIX] - Fixed the test on mac for testGetOsShell

- src/main/java/CIServer.java
- src/main/java/Firebase/PullRequest.java
Added the conncetion to database when push is alerted by the server. Also added comment and refactored for better reading.
> [ADD], added the method for push #77

- src/main/java/CIServer.java
Fixed and changed the input to createClassPull and Push so that the
input is a jasonString instead. So that they no longer point to null.
> [FIX] - Fixed bug with create class according to issue #84

- client/src/components/buildsTable.js
Added component buildtable that displays a set of cards, containing build info
> [ADD] Added component buildstable that lists build cards

- client/src/components/spinner.js
Added seperate component spinner, to avoid duplicating styling
> [ADD] Added new component spinner

- client/src/pages/builds.js
- client/src/pages/home.js
- client/src/pages/notFound.js
- client/src/pages/singleBuild.js
Added page skeletons to be able to test navigation
> [ADD] Added skeleton for pages close #96

- client/src/util/hooks.js
Added hooks to serve as an interface for the builds context
> [ADD] Added hooks that serve as an interface for the context

- client/src/components/card.js
Added presentational card component to show surface level data about build
> [ADD] Added card component to display surface level data about build

- client/src/components/nav.js
Added simple nav to navigate through views
> [ADD] Added nav component to navigate through views 

- client/package.json
Added client dependenceis to package.json for easy installation
> [ADD] Added dependencies to package.json  close #94

- client/src/components/withLoader.js
Added withLoader that shows spinner while data is fetching
> [ADD] Added helpercomponent withLoader close #91

- src/main/java/CIServer.java
- src/main/java/Firebase/BuildResult.java
- src/main/java/Firebase/Data.java
- src/main/java/Firebase/Database.java
- src/main/java/Firebase/PullRequest.java
- src/main/java/Firebase/Type.java
- src/main/java/Firebase/User.java
Added the information to the classes and method in server form documentation.
> [ADD], added the infromation for the documentation #117

- client/src/pages/builds.js
Added builds page to display all builds in cards
> [ADD] Added builds page

- client/src/pages/home.js
Added home page to display most recent builds
> [ADD] Added home page

- client/src/pages/singleBuild.js
Added page single build to display info about a single build
> [ADD] Added page single build

- client/src/pages/notFound.js
Added 404 page to show when non matching routes are entered
> [ADD] Added 404 page

- client/src/App.js
Added routing in main app component to different sub pages
> [ADD] Added routing to app component

- src/main/java/CIServer.java
Fixed the id problem for the target_url in status_API().
close #121
> [FIX] - id problem in status_API()

- src/main/java/CIServer.java
Fixed bug with if statements in CIServer.java so that the correct array
element is checked rather than the whole array. close #120
> [FIX] - Fixed bug in if in CIserver.java according to issue #120

- src/main/java/CIServer.java
- src/main/java/ServerControl.java
Changed the script in cloneAndBuildWin to instead use gradlew build so that the test are run
when building. close #124
>  [REFACTOR] - Changed build script according to issue #124

- src/main/java/CIServer.java
Changed the URL in status_API(). 
close #126
>  [FIX] - URL problem in status_API()

- src/main/java/CIServer.java
- src/main/java/Firebase/PullRequest.java
Added get_message_push to database.
> [ADD], Added the method for message in push #131

- src/main/java/JsonParser.java
> [ADD], Added the information in JsonParser for document #134

- README.md
Adding the README.md
close #82
> [ADD] - Add information about program and methods in README
